#include "edat.h"

void edat::Initialize() {
    HELPER_MIRROR_MOVE[MOVE_SURFACE_CW] = MOVE_SURFACE_CCW;
    HELPER_MIRROR_MOVE[MOVE_SURFACE_CCW] = MOVE_SURFACE_CW;
    HELPER_MIRROR_MOVE[MOVE_WANDER_CW] = MOVE_WANDER_CCW;
    HELPER_MIRROR_MOVE[MOVE_WANDER_CCW] = MOVE_WANDER_CW;
    MAP_TILETYPE_TO_TILEID[0] = 6;
    MAP_TILETYPE_TO_TILEID[1] = 26;
    MAP_TILETYPE_TO_TILEID[2] = 18;
    MAP_TILETYPE_TO_TILEID[3] = 14;
    MAP_TILETYPE_TO_TILEID[4] = 2;
    MAP_TILETYPE_TO_TILEID[5] = 30;
    MAP_TILETYPE_TO_TILEID[6] = 22;
    MAP_TILETYPE_TO_TILEID[7] = 10;
    //MAP_ETYPE_TO_MC[ETYPE_PLAYER] = asset_editor_gfx_player;
    //MAP_ETYPE_TO_MC[ETYPE_BOUNCEBLOCK] = asset_editor_gfx_bounceblock;
    //MAP_ETYPE_TO_MC[ETYPE_DOOR_REGULAR] = asset_editor_gfx_door_regular;
    //MAP_ETYPE_TO_MC[ETYPE_DOOR_LOCKED] = asset_editor_gfx_door_locked;
    //MAP_ETYPE_TO_MC[ETYPE_SWITCH_LOCKED] = asset_editor_gfx_switch_locked;
    //MAP_ETYPE_TO_MC[ETYPE_DOOR_TRAP] = asset_editor_gfx_door_trap;
    //MAP_ETYPE_TO_MC[ETYPE_SWITCH_TRAP] = asset_editor_gfx_switch_trap;
    //MAP_ETYPE_TO_MC[ETYPE_CHAINGUN] = asset_editor_gfx_chaingun;
    //MAP_ETYPE_TO_MC[ETYPE_LASER] = asset_editor_gfx_laser;
    //MAP_ETYPE_TO_MC[ETYPE_ZAP] = asset_editor_gfx_zap;
    //MAP_ETYPE_TO_MC[ETYPE_CHASER] = asset_editor_gfx_chaser;
    //MAP_ETYPE_TO_MC[ETYPE_EXIT_DOOR] = asset_editor_gfx_exit_door;
    //MAP_ETYPE_TO_MC[ETYPE_EXIT_SWITCH] = asset_editor_gfx_exit_switch;
    //MAP_ETYPE_TO_MC[ETYPE_FLOORGUARD] = asset_editor_gfx_floorguard;
    //MAP_ETYPE_TO_MC[ETYPE_GOLD] = asset_editor_gfx_gold;
    //MAP_ETYPE_TO_MC[ETYPE_LAUNCHPAD] = asset_editor_gfx_launchpad;
    //MAP_ETYPE_TO_MC[ETYPE_MINE] = asset_editor_gfx_mine;
    //MAP_ETYPE_TO_MC[ETYPE_ONEWAY] = asset_editor_gfx_oneway;
    //MAP_ETYPE_TO_MC[ETYPE_ROCKET] = asset_editor_gfx_rocket;
    //MAP_ETYPE_TO_MC[ETYPE_TURRET] = asset_editor_gfx_turret;
    //MAP_ETYPE_TO_MC[ETYPE_THWOMP] = asset_editor_gfx_thwomp;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_PLAYER] = asset_editor_gfx_player_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_BOUNCEBLOCK] = asset_editor_gfx_bounceblock_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_DOOR_REGULAR] = asset_editor_gfx_door_regular_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_DOOR_LOCKED] = asset_editor_gfx_door_locked_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_SWITCH_LOCKED] = asset_editor_gfx_switch_locked_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_DOOR_TRAP] = asset_editor_gfx_door_trap_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_SWITCH_TRAP] = asset_editor_gfx_switch_trap_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_CHAINGUN] = asset_editor_gfx_chaingun_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_LASER] = asset_editor_gfx_laser_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_ZAP] = asset_editor_gfx_zap_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_CHASER] = asset_editor_gfx_chaser_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_EXIT_DOOR] = asset_editor_gfx_exit_door_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_EXIT_SWITCH] = asset_editor_gfx_exit_switch_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_FLOORGUARD] = asset_editor_gfx_floorguard_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_GOLD] = asset_editor_gfx_gold_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_LAUNCHPAD] = asset_editor_gfx_launchpad_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_MINE] = asset_editor_gfx_mine_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_ONEWAY] = asset_editor_gfx_oneway_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_ROCKET] = asset_editor_gfx_rocket_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_TURRET] = asset_editor_gfx_turret_SEL;
    //MAP_ETYPE_TO_MC_SELECTED[ETYPE_THWOMP] = asset_editor_gfx_thwomp_SEL;
    HELPER_MAP_DIR_TO_VEC[DIR_R] = vec2(1,0);
    HELPER_MAP_DIR_TO_VEC[DIR_RD] = vec2(1/sqrt(2),1/sqrt(2));
    HELPER_MAP_DIR_TO_VEC[DIR_D] = vec2(0,1);
    HELPER_MAP_DIR_TO_VEC[DIR_LD] = vec2(-1/sqrt(2),1/sqrt(2));
    HELPER_MAP_DIR_TO_VEC[DIR_L] = vec2(-1,0);
    HELPER_MAP_DIR_TO_VEC[DIR_LU] = vec2(-1/sqrt(2),-1/sqrt(2));
    HELPER_MAP_DIR_TO_VEC[DIR_U] = vec2(0,-1);
    HELPER_MAP_DIR_TO_VEC[DIR_RU] = vec2(1/sqrt(2),-1/sqrt(2));
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_PLAYER] = vec2(10,-1);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_BOUNCEBLOCK] = vec2(9.6,9.6);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_DOOR_REGULAR] = vec2(12,-1);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_DOOR_LOCKED] = vec2(12,-1);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_SWITCH_LOCKED] = vec2(4,4);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_DOOR_TRAP] = vec2(12,-1);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_SWITCH_TRAP] = vec2(4,4);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_CHAINGUN] = vec2(9,-1);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_LASER] = vec2(9,-1);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_ZAP] = vec2(9,-1);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_CHASER] = vec2(9,-1);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_EXIT_DOOR] = vec2(12,12);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_EXIT_SWITCH] = vec2(6,4);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_FLOORGUARD] = vec2(6,-1);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_GOLD] = vec2(4,4);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_LAUNCHPAD] = vec2(8,-1);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_MINE] = vec2(4,-1);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_ONEWAY] = vec2(12,-1);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_ROCKET] = vec2(6,-1);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_TURRET] = vec2(6,-1);
    HELPER_MAP_ETYPE_TO_COLSHAPE[ETYPE_THWOMP] = vec2(9,9);
    STRUCT_SIZE[STRUCTTYPE_PLAYER] = 2;
    STRUCT_SIZE[STRUCTTYPE_BOUNCEBLOCK] = 2;
    STRUCT_SIZE[STRUCTTYPE_DOOR_REGULAR] = 3;
    STRUCT_SIZE[STRUCTTYPE_DOOR_LOCKED] = 5;
    STRUCT_SIZE[STRUCTTYPE_DOOR_TRAP] = 5;
    STRUCT_SIZE[STRUCTTYPE_CHAINGUN] = 4;
    STRUCT_SIZE[STRUCTTYPE_LASER] = 4;
    STRUCT_SIZE[STRUCTTYPE_ZAP] = 4;
    STRUCT_SIZE[STRUCTTYPE_CHASER] = 4;
    STRUCT_SIZE[STRUCTTYPE_EXIT] = 4;
    STRUCT_SIZE[STRUCTTYPE_FLOORGUARD] = 2;
    STRUCT_SIZE[STRUCTTYPE_GOLD] = 2;
    STRUCT_SIZE[STRUCTTYPE_LAUNCHPAD] = 3;
    STRUCT_SIZE[STRUCTTYPE_MINE] = 2;
    STRUCT_SIZE[STRUCTTYPE_ONEWAY] = 3;
    STRUCT_SIZE[STRUCTTYPE_ROCKET] = 2;
    STRUCT_SIZE[STRUCTTYPE_TURRET] = 2;
    STRUCT_SIZE[STRUCTTYPE_THWOMP] = 3;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_BOUNCEBLOCK] = ETYPE_BOUNCEBLOCK;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_CHAINGUN] = ETYPE_CHAINGUN;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_CHASER] = ETYPE_CHASER;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_DOOR_LOCKED] = ETYPE_DOOR_LOCKED;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_DOOR_REGULAR] = ETYPE_DOOR_REGULAR;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_DOOR_TRAP] = ETYPE_DOOR_TRAP;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_EXIT] = ETYPE_EXIT_DOOR;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_FLOORGUARD] = ETYPE_FLOORGUARD;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_GOLD] = ETYPE_GOLD;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_LASER] = ETYPE_LASER;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_LAUNCHPAD] = ETYPE_LAUNCHPAD;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_MINE] = ETYPE_MINE;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_ONEWAY] = ETYPE_ONEWAY;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_PLAYER] = ETYPE_PLAYER;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_ROCKET] = ETYPE_ROCKET;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_THWOMP] = ETYPE_THWOMP;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_TURRET] = ETYPE_TURRET;
    MAP_STRUCT_TO_ETYPE[STRUCTTYPE_ZAP] = ETYPE_ZAP;
}

vec2 edat::GET_WORLDSPACE_POS(const vector<unsigned int>& data) {
    return vec2(data[EPROP_X] * quantize_step_size, data[EPROP_Y] * quantize_step_size);
}

vec2 edat::MAP_DIR_TO_VEC(int direction) {
    return HELPER_MAP_DIR_TO_VEC[direction].Clone();
}

vec2 edat::GET_COLLISION_SHAPE(const vector<unsigned int>& data) {
    return HELPER_MAP_ETYPE_TO_COLSHAPE[data[EPROP_TYPE]].Clone();
}